[package]
name = "versionwatch-collect"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
config = { workspace = true }
futures = { workspace = true }
polars = { workspace = true }
reqwest = { workspace = true }
rss = { workspace = true }
scraper = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
versionwatch-core = { path = "../versionwatch-core" }
versionwatch-config = { path = "../versionwatch-config" }
regex = { workspace = true }

[dev-dependencies]
httpmock = { workspace = true }
