# List of software targets to track.
#
# Each target represents a piece of software to monitor.
#
# Configuration:
#   name: The official name of the software. This must be unique and match a collector implementation.
#   enabled: Set to `true` to track this software, `false` to ignore.
#
# All collectors now use dedicated implementations with intelligent fallback strategies:
# - Primary sources: Official APIs, Docker Hub, Maven Central, MetaCPAN, etc.
# - Fallback sources: GitHub API, known stable versions
# - Automatic rate limiting detection and source switching
#
# No additional configuration is needed - each collector handles its own data sources.

targets:
  # ✅ Collecteurs migrés vers Polars DataFrame (Phase 6.2 terminée)
  - name: "node"
    enabled: true

  - name: "docker"
    enabled: true

  - name: "go"
    enabled: true

  - name: "perl"
    enabled: true

  - name: "apache"
    enabled: true

  - name: "php"
    enabled: true

  - name: "eclipse-temurin"
    enabled: true

  - name: "swift"
    enabled: true

  - name: "kong"
    enabled: true

  - name: "caddy"
    enabled: true

  - name: "mysql"
    enabled: true

  - name: "postgresql"
    enabled: true

  - name: "mongodb"
    enabled: true

  # ✅ Collecteurs réintégrés (Phase 6.3+)
  - name: "rust"
    enabled: true

  - name: "python"
    enabled: true

  - name: "nginx"
    enabled: true

  - name: "ruby"
    enabled: true

  - name: "scala"
    enabled: true

  - name: "kotlin"
    enabled: true
    