# List of software targets to track.
#
# Each target represents a piece of software to monitor.
#
# Fields:
#   name: The official name of the software. This must be unique.
#   enabled: Set to `true` to track this software, `false` to ignore.
#   type: (Optional) The type of collector to use. For GitHub, set this to "github".
#         If omitted, a specific collector implementation must exist.
#   repository: (Required if type is "github") The GitHub repository in "owner/repo" format.
#   github_source: (Optional, for "github" type) The source for versioning.
#                  Can be "releases" (default) or "tags". Use "tags" for projects
#                  that use git tags for versioning instead of formal releases.

targets:
  - name: "node"
    enabled: true

  - name: "docker"
    enabled: true
    type: github
    repository: "moby/moby"

  - name: "rust"
    enabled: true
    type: github
    repository: "rust-lang/rust"

  - name: "python"
    enabled: true
    type: github
    repository: "python/cpython"
    github_source: "tags"

  - name: "eclipse-temurin"
    enabled: true

  - name: "php"
    enabled: true

  - name: "go"
    enabled: true

  - name: "nginx"
    enabled: true
    type: "github_releases"
    repository: "nginx/nginx"

  - name: "ruby"
    enabled: true
    type: github
    repository: "ruby/ruby"

  - name: "elixir"
    enabled: true
    type: github
    repository: "elixir-lang/elixir"

  - name: "scala"
    enabled: true
    type: github
    repository: "scala/scala"

  - name: "kotlin"
    enabled: true
    type: github
    repository: "JetBrains/kotlin"

  - name: "swift"
    enabled: true
    type: github
    repository: "apple/swift"

  - name: "perl"
    enabled: true

  - name: "kong"
    enabled: true
    type: github
    repository: "Kong/kong"

  - name: "apache"
    enabled: true

  - name: "caddy"
    enabled: true
    type: "github_releases"
    repository: "caddyserver/caddy"
    